{% set version = "1.1-2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-th.data
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/TH.data_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/TH.data/TH.data_{{ version }}.tar.gz
  sha256: 47f94eb57b6fcef42efa30824c1356bf10529c4b94b0d0acdb787b434dddde73

build:
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-survival
  run:
    - r-base
    - r-mass
    - r-survival

test:
  commands:
    - $R -e "library('TH.data')"           # [not win]
    - "\"%R%\" -e \"library('TH.data')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=TH.data
  license: GPL-3
  summary: Contains data sets used in other packages Torsten Hothorn maintains.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: TH.data
# Title: TH's Data Archive
# Date: 2019-01-22
# Version: 1.0-10
# Authors@R: c(person("Torsten", "Hothorn", role = c("aut", "cre"), email = "Torsten.Hothorn@R-project.org"))
# Description: Contains data sets used in other packages Torsten Hothorn maintains.
# Depends: R (>= 2.10.0), survival, MASS
# Suggests: dplyr, gdata, plyr
# LazyData: yes
# License: GPL-3
# NeedsCompilation: no
# Packaged: 2019-01-21 10:36:50 UTC; hothorn
# Author: Torsten Hothorn [aut, cre]
# Maintainer: Torsten Hothorn <Torsten.Hothorn@R-project.org>
# Repository: CRAN
# Date/Publication: 2019-01-21 11:10:03 UTC
