appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: Facdr8/Q/cMkMfumFWmzCxh2s7uht34FNqCdcE6NmZY9KFSs5fHYWvReaDqIObSbIM1XqX0dw/6PEomBZfacGE6x0cTfWCYveWnOho+zxIBQQK7I2gQHbSckWu2FF7R7E23HVXb/pKAIytb2+l3VARhUScUR0fo4j7T8tu47Os4LX99n09H2DCOSAyITcJxguRTPdaoCetToRPzBYpB7K45y7Bytvq9P7zu7QJRVToq4cH9NFnpuMoNkSZXQAqz4DT5miM4KIB111sSLwcua2H5MEKFtZMRupbklWXNx9h7UXRZxNhpIljcWLs4e+qEdX4zT7HwZ1j9aqaSnw46cQdHwAow/6EDqU5teHwHufF13cKDuvwLUljB54oFtv5CADw/OyrVYKPq4bTUdE/EBOGIT8M6gl8w69ahZKvW2hjuzOvimYNRkx/Gm9IlInfy95FDMQOiEv3z+EcsmJXt1E+pu+fHjSfp68hAPPUtah+v3ojFKDvU1TYDjtf/xVOq2ZGK22j0V/NMEQvR24k0TcSZv77XFGOgVa62wKw2STw0t3MgXv4Jz2fYrhZYGijdUvVi/uIIKoLHm9UReRVlOywFPiLUMB+o5F04xC+zF3c1CF5Y/MVOCXE8u1AoXmKDOTV+PhKUzzv9m1MqnVJmsD6YKUcaCr9GNpg1wP4WCxYk=}
bot:
  automerge: true
